#!/bin/bash

gh issue create --title "[AIKIT-31] Pre-built usage dashboard" --body "**Story Points:** 8" --label "epic:cost-observability,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-32] Prompt injection detection" --body "**Story Points:** 13" --label "epic:safety-guardrails,story-points:13,phase:3-advanced"
gh issue create --title "[AIKIT-33] Jailbreak detection" --body "**Story Points:** 8" --label "epic:safety-guardrails,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-34] PII detection" --body "**Story Points:** 13" --label "epic:safety-guardrails,story-points:13,phase:3-advanced"
gh issue create --title "[AIKIT-35] Custom PII patterns" --body "**Story Points:** 5" --label "epic:safety-guardrails,story-points:5,phase:3-advanced"
gh issue create --title "[AIKIT-36] Content moderation" --body "**Story Points:** 8" --label "epic:safety-guardrails,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-37] Rate limiting" --body "**Story Points:** 8" --label "epic:safety-guardrails,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-38] Next.js route helpers" --body "**Story Points:** 5" --label "epic:framework-adapters,story-points:5,phase:2-multi-framework"
gh issue create --title "[AIKIT-39] Next.js middleware helpers" --body "**Story Points:** 8" --label "epic:framework-adapters,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-40] Test utilities" --body "**Story Points:** 8" --label "epic:framework-adapters,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-41] AINative Auth integration" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-42] Session management" --body "**Story Points:** 5" --label "epic:ecosystem-integration,story-points:5,phase:2-multi-framework"
gh issue create --title "[AIKIT-43] RLHF logging" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-44] RLHF auto-instrumentation" --body "**Story Points:** 5" --label "epic:ecosystem-integration,story-points:5,phase:2-multi-framework"
gh issue create --title "[AIKIT-45] ZeroDB CRUD operations" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-46] ZeroDB as agent tool" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:2-multi-framework"
gh issue create --title "[AIKIT-47] Design token extraction" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-48] Design validation" --body "**Story Points:** 8" --label "epic:ecosystem-integration,story-points:8,phase:3-advanced"
gh issue create --title "[AIKIT-49] Design constraints for prompts" --body "**Story Points:** 5" --label "epic:ecosystem-integration,story-points:5,phase:3-advanced"
gh issue create --title "[AIKIT-50] API reference docs" --body "**Story Points:** 13" --label "epic:developer-experience,story-points:13,phase:4-launch"

echo "Created issues 31-50!"
