#!/bin/bash

gh issue create --title "[AIKIT-51] Getting started guide" --body "**Story Points:** 8" --label "epic:developer-experience,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-52] Framework-specific guides" --body "**Story Points:** 13" --label "epic:developer-experience,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-53] Example chat apps" --body "**Story Points:** 13" --label "epic:developer-experience,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-54] Example agent apps" --body "**Story Points:** 13" --label "epic:developer-experience,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-55] Example dashboard apps" --body "**Story Points:** 8" --label "epic:developer-experience,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-56] CLI to scaffold new projects" --body "**Story Points:** 13" --label "epic:developer-experience,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-57] CLI to test prompts" --body "**Story Points:** 8" --label "epic:developer-experience,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-58] Full TypeScript type safety" --body "**Story Points:** 8" --label "epic:developer-experience,story-points:8,phase:1-mvp"
gh issue create --title "[AIKIT-59] Comprehensive unit tests" --body "**Story Points:** 21" --label "epic:testing-quality,story-points:21,phase:1-mvp"
gh issue create --title "[AIKIT-60] Integration tests" --body "**Story Points:** 13" --label "epic:testing-quality,story-points:13,phase:2-multi-framework"
gh issue create --title "[AIKIT-61] E2E tests" --body "**Story Points:** 13" --label "epic:testing-quality,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-62] Performance benchmarks" --body "**Story Points:** 8" --label "epic:testing-quality,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-63] Publish NPM packages" --body "**Story Points:** 8" --label "epic:publishing-distribution,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-64] Separate packages for optional features" --body "**Story Points:** 5" --label "epic:publishing-distribution,story-points:5,phase:4-launch"
gh issue create --title "[AIKIT-65] CDN bundles" --body "**Story Points:** 5" --label "epic:publishing-distribution,story-points:5,phase:4-launch"
gh issue create --title "[AIKIT-66] Organized GitHub repo" --body "**Story Points:** 5" --label "epic:publishing-distribution,story-points:5,phase:4-launch"
gh issue create --title "[AIKIT-67] Security audit" --body "**Story Points:** 13" --label "epic:launch-readiness,story-points:13,phase:4-launch"
gh issue create --title "[AIKIT-68] Performance audit" --body "**Story Points:** 8" --label "epic:launch-readiness,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-69] Beta testing" --body "**Story Points:** 8" --label "epic:launch-readiness,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-70] Marketing site" --body "**Story Points:** 8" --label "epic:launch-readiness,story-points:8,phase:4-launch"
gh issue create --title "[AIKIT-71] Discord community" --body "**Story Points:** 3" --label "epic:launch-readiness,story-points:3,phase:4-launch"

echo "Created issues 51-71! All 71 issues completed!"
