name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the sections below.

  - type: textarea
    id: summary
    attributes:
      label: Feature Summary
      description: Brief description of the feature
      placeholder: What feature would you like to see?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm trying to do X but currently have to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Design (Optional)
      description: If applicable, show how the API would look
      render: typescript
      placeholder: |
        // Example usage
        const { data } = useNewFeature({
          option: 'value'
        })
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered?
      placeholder: I also considered...
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which package should this feature be added to?
      options:
        - "@ainative/ai-kit-core"
        - "@ainative/ai-kit (React)"
        - "@ainative/ai-kit-safety"
        - "@ainative/ai-kit-cli"
        - "@ainative/ai-kit-video"
        - "@ainative/ai-kit-nextjs"
        - "@ainative/ai-kit-svelte"
        - "@ainative/ai-kit-vue"
        - "@ainative/ai-kit-testing"
        - "@ainative/ai-kit-observability"
        - "@ainative/ai-kit-tools"
        - "@ainative/ai-kit-auth"
        - "@ainative/ai-kit-rlhf"
        - "@ainative/ai-kit-zerodb"
        - "@ainative/ai-kit-design-system"
        - "New package"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my work"
        - "High - Important for my use case"
        - "Medium - Would be nice to have"
        - "Low - Minor improvement"
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case
      placeholder: I'm building an app that needs to...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other relevant information
      placeholder: Add any other context, screenshots, or examples here
    validations:
      required: false

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
        - label: I have considered if this could be solved with existing features
          required: true
        - label: I am willing to help implement this feature
          required: false
