name: Feature Request
description: Suggest a new feature or enhancement for AI Kit
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: "I've also considered..."
    validations:
      required: false

  - type: dropdown
    id: package
    attributes:
      label: Package
      description: Which AI Kit package should this feature be added to?
      options:
        - "@ainative/ai-kit-core"
        - "@ainative/ai-kit-react"
        - "@ainative/ai-kit-nextjs"
        - "@ainative/ai-kit-tools"
        - "@ainative/ai-kit-testing"
        - "@ainative/ai-kit-vue"
        - "@ainative/ai-kit-svelte"
        - "@ainative/ai-kit-cli"
        - "@ainative/ai-kit-video"
        - "@ainative/ai-kit-community"
        - "New Package"
        - "Not sure"
    validations:
      required: true

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - "New API/Function"
        - "New Component"
        - "New Hook"
        - "New Tool"
        - "Performance Improvement"
        - "Developer Experience"
        - "Documentation"
        - "Testing"
        - "Security"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Critical - Blocking my work"
        - "High - Significantly improves my workflow"
        - "Medium - Nice to have"
        - "Low - Would be useful eventually"
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature
      placeholder: "In my application, I need to..."
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Desired API/Usage Example
      description: Show how you would like to use this feature (pseudo-code is fine)
      placeholder: |
        ```typescript
        import { newFeature } from '@ainative/ai-kit-core';

        const result = newFeature({
          // example usage
        });
        ```
      render: typescript
    validations:
      required: false

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: What are the benefits of implementing this feature?
      placeholder: |
        - Improves performance by...
        - Makes it easier to...
        - Enables new use cases like...
    validations:
      required: false

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: Would this feature require any breaking changes to existing APIs?
      placeholder: "This would require changing..."
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear use case for this feature
          required: true
        - label: I am willing to help implement or test this feature
          required: false
